# Base Docker Compose configuration
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=crawler_user
      - DB_PASSWORD=crawler_password
      - DB_NAME=crawler_db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=crawler_db
      - MYSQL_USER=crawler_user
      - MYSQL_PASSWORD=crawler_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mysql_data: